//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOD_Resource_BranchEntities : DbContext
    {
        public MOD_Resource_BranchEntities()
            : base("name=MOD_Resource_BranchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_TextBook> tb_TextBook { get; set; }
        public virtual DbSet<tb_Resource> tb_Resource { get; set; }
    }
}
