//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxOms.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class box_update_sys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public box_update_sys()
        {
            this.box_update_sys_log = new HashSet<box_update_sys_log>();
        }
    
        public int Id { get; set; }
        public double VNumber { get; set; }
        public string PackUrl { get; set; }
        public string Principal { get; set; }
        public string Cause { get; set; }
        public bool IsPublish { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<box_update_sys_log> box_update_sys_log { get; set; }
    }
}
