//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxOms.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class box_resource_statist_day
    {
        public string Id { get; set; }
        public int BoxId { get; set; }
        public string Mac { get; set; }
        public System.DateTime SDate { get; set; }
        public Nullable<int> Subject { get; set; }
        public Nullable<int> Edition { get; set; }
        public int f0 { get; set; }
        public int f1 { get; set; }
        public int f2 { get; set; }
        public int f3 { get; set; }
        public int f4 { get; set; }
        public int f5 { get; set; }
        public int f6 { get; set; }
        public int f7 { get; set; }
        public int f8 { get; set; }
        public int f9 { get; set; }
        public int f10 { get; set; }
        public int f11 { get; set; }
        public int f12 { get; set; }
        public int EditionTotal { get; set; }
        public int SubjectTotal { get; set; }
    }
}
