//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxOms.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class box_resource_statist
    {
        public string Id { get; set; }
        public int BoxId { get; set; }
        public string Mac { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> Subject { get; set; }
        public Nullable<int> Edition { get; set; }
        public int Type { get; set; }
        public string TypeName { get; set; }
    }
}
