//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxOms.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class box_omsEntities : DbContext
    {
        public box_omsEntities()
            : base("name=box_omsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<box_good> box_good { get; set; }
        public virtual DbSet<box_good_online> box_good_online { get; set; }
        public virtual DbSet<box_resource_statist> box_resource_statist { get; set; }
        public virtual DbSet<box_resource_statist_day> box_resource_statist_day { get; set; }
        public virtual DbSet<box_subject_edition> box_subject_edition { get; set; }
        public virtual DbSet<box_update_sys> box_update_sys { get; set; }
        public virtual DbSet<box_update_sys_log> box_update_sys_log { get; set; }
        public virtual DbSet<oms_district> oms_district { get; set; }
        public virtual DbSet<rp_cdkey> rp_cdkey { get; set; }
        public virtual DbSet<rp_cdkey_and_edition> rp_cdkey_and_edition { get; set; }
        public virtual DbSet<rp_enterprise> rp_enterprise { get; set; }
        public virtual DbSet<rp_log_login> rp_log_login { get; set; }
        public virtual DbSet<sys_role> sys_role { get; set; }
        public virtual DbSet<sys_role_and_auth> sys_role_and_auth { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<sys_user_and_role> sys_user_and_role { get; set; }
        public virtual DbSet<rp_resource_statist> rp_resource_statist { get; set; }
    }
}
