//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoxOms.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class rp_cdkey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rp_cdkey()
        {
            this.rp_cdkey_and_edition = new HashSet<rp_cdkey_and_edition>();
            this.rp_resource_statist = new HashSet<rp_resource_statist>();
            this.rp_log_login = new HashSet<rp_log_login>();
        }
    
        public string Id { get; set; }
        public Nullable<int> EntId { get; set; }
        public Nullable<int> UseProv { get; set; }
        public Nullable<int> UseCity { get; set; }
        public Nullable<int> UseDist { get; set; }
        public string UseSchool { get; set; }
        public Nullable<int> Validity { get; set; }
        public Nullable<System.DateTime> ExpirTime { get; set; }
        public Nullable<int> AuthUserCount { get; set; }
        public string UseUser { get; set; }
        public string ActiveMac { get; set; }
        public string ActiveDisk { get; set; }
        public Nullable<System.DateTime> ActiveTime { get; set; }
        public string ActiveIp { get; set; }
        public string ActiveCode { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rp_cdkey_and_edition> rp_cdkey_and_edition { get; set; }
        public virtual rp_enterprise rp_enterprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rp_resource_statist> rp_resource_statist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rp_log_login> rp_log_login { get; set; }
    }
}
